/* 
 * AnalysisBackend
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Threading.Tasks;
using NUnit.Framework;
using ProWritingAid.SDK.Api.Async;
using ProWritingAid.SDK.Client;
using ProWritingAid.SDK.Model;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AsyncWordCloudApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AsyncWordCloudApiTests : ApiTestsBase<WordCloudAsyncApi>
    {
        public AsyncWordCloudApiTests() : base(new WordCloudAsyncApi(Config))
        {
        }

        [Test]
        public void CanGetResults()
        {
            var request = new WordCloudRequest(
                ShortSampleText,
                WordCloudRequest.OrientationEnum.EveryWhichWay,
                WordCloudRequest.CaseMethodEnum.IntelligentCase,
                "Earthy",
                Int32.MaxValue,
                true,
                "Arial",
                500,
                500,
                false,
                WordCloudRequest.StyleEnum.General,
                WordCloudRequest.LanguageEnum.En,
                LicenseCredentials);

            var res = Api.WordCloudPost(request);

            Assert.That(res, Is.Not.Null);
            Assert.That(res.Url, Is.Not.Null);
            Assert.That(res.Url, Is.Not.Empty);
        }

        [Test]
        public async Task CanGetResultsAsync()
        {
            var request = new WordCloudRequest(
                ShortSampleText,
                WordCloudRequest.OrientationEnum.EveryWhichWay,
                WordCloudRequest.CaseMethodEnum.IntelligentCase,
                "Earthy",
                Int32.MaxValue,
                true,
                "Arial",
                500,
                500,
                false,
                WordCloudRequest.StyleEnum.General,
                WordCloudRequest.LanguageEnum.En,
                LicenseCredentials);

            var res = await Api.WordCloudPostAsync(request);

            Assert.That(res, Is.Not.Null);
            Assert.That(res.Url, Is.Not.Null);
            Assert.That(res.Url, Is.Not.Empty);
        }
    }
}