/* 
 * AnalysisBackend
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Threading.Tasks;
using NUnit.Framework;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Api.Async;
using ProWritingAid.SDK.Client;
using ProWritingAid.SDK.Model;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AsyncSummaryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AsyncSummaryApiTests : ApiTestsBase<SummaryAsyncApi>
    {
        public AsyncSummaryApiTests() : base(new SummaryAsyncApi(Config))
        {
        }

        [Test]
        public void CantAccessServiceWithInvalidLicense()
        {
            var request = new SummaryAnalysisRequest(
                LongSampleText,
                new AnalysisSettings(),
                SummaryAnalysisRequest.StyleEnum.General,
                SummaryAnalysisRequest.LanguageEnum.En,
                InvalidCredentials);
            Assert.Throws<ApiException>(() => Api.SummaryPost(request));
        }

        /// <summary>
        /// Test AsyncHtmlPost
        /// </summary>
        [Test]
        public void CanProcessShortTextsSynchronously()
        {
            var api = new AsyncSummaryApi(Config);
            var request = new SummaryAnalysisRequest(
                ShortSampleText,
                new AnalysisSettings(),
                SummaryAnalysisRequest.StyleEnum.General,
                SummaryAnalysisRequest.LanguageEnum.En,
                LicenseCredentials);

            var response = api.AsyncSummaryPost(request);


            Assert.That(response, Is.Not.Null);
            Assert.That(response.Result, Is.Not.Null);
            Assert.That(response.Result.Text, Is.Not.Null);
            Assert.That(response.Result.Text, Is.Not.Empty);
        }

        /// <summary>
        /// Test SummaryPost
        /// </summary>
        [Test]
        public void CanGetResult()
        {
            var request = new SummaryAnalysisRequest(
                LongSampleText,
                new AnalysisSettings(),
                SummaryAnalysisRequest.StyleEnum.General,
                SummaryAnalysisRequest.LanguageEnum.En,
                LicenseCredentials);
            var response = Api.SummaryPost(request);
            Assert.That(response, Is.Not.Null);
            Assert.That(response.Text, Is.Not.Null);
            Assert.That(response.Text, Is.Not.Empty);
        }

        /// <summary>
        /// Test SummaryPost
        /// </summary>
        [Test]
        public async Task CanGetResultAsync()
        {
            var request = new SummaryAnalysisRequest(
                LongSampleText,
                new AnalysisSettings(),
                SummaryAnalysisRequest.StyleEnum.General,
                SummaryAnalysisRequest.LanguageEnum.En,
                LicenseCredentials);
            var response = await Api.SummaryPostAsync(request);
            Assert.That(response, Is.Not.Null);
            Assert.That(response.Text, Is.Not.Null);
            Assert.That(response.Text, Is.Not.Empty);
        }
    }
}