/* 
 * AnalysisBackend
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Dynamic;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;
using ProWritingAid.SDK.Client;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing HtmlApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HtmlApiTests : ApiTestsBase<HtmlApi>
    {
        public HtmlApiTests() : base(new HtmlApi(Config))
        {
        }

        [Test]
        public void CantAccessServiceWithInvalidLicense()
        {
            var request = new HtmlAnalysisRequest(
                ShortSampleText,
                new List<string> {"grammar"},
                HtmlAnalysisRequest.StyleEnum.General,
                HtmlAnalysisRequest.LanguageEnum.En,
                InvalidCredentials);
            Assert.Throws<ApiException>(() => Api.HtmlPost(request));
        }

        /// <summary>
        /// Test HtmlPost
        /// </summary>
        [Test]
        public void HtmlPostTest()
        {
            var request = new HtmlAnalysisRequest(
                ShortSampleText,
                new List<string> {"grammar"},
                HtmlAnalysisRequest.StyleEnum.General,
                HtmlAnalysisRequest.LanguageEnum.En,
                LicenseCredentials);
            var response = Api.HtmlPost(request);
            Assert.That(response, Is.Not.Null);
            Assert.That(response.Summaries, Is.Not.Empty);
        }
    }
}