/* 
 * AnalysisBackend
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Client;
using ProWritingAid.SDK.Model;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing TextApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TextApiTests : ApiTestsBase<TextApi>
    {
        public TextApiTests() : base(new TextApi(Config))
        {
        }
        
        [Test]
        public void CantAccessServiceWithInvalidLicense()
        {
            var request = new TextAnalysisRequest(
                ShortSampleText,
                new List<string> {"grammar"},
                TextAnalysisRequest.StyleEnum.General,
                TextAnalysisRequest.LanguageEnum.En,
                InvalidCredentials);
            Assert.Throws<ApiException>(() => Api.TextPost(request));
        }

        /// <summary>
        /// Test TextPost
        /// </summary>
        [Test]
        public void TextPostTest()
        {
            var request = new TextAnalysisRequest(
                LongSampleText,
                new List<string> {"grammar"},
                TextAnalysisRequest.StyleEnum.General,
                TextAnalysisRequest.LanguageEnum.En,
                LicenseCredentials);
            var response = Api.TextPost(request);
            Assert.That(response, Is.Not.Null);
            Assert.That(response.Summaries, Is.Not.Empty);
            Assert.That(response.Tags, Is.Not.Empty);
        }


        [Test]
        public void CanUseSameClientInParallel()
        {
            var req = new TextAnalysisRequest(
                ShortSampleText,
                new List<string> {"grammar"},
                TextAnalysisRequest.StyleEnum.General,
                TextAnalysisRequest.LanguageEnum.En,
                LicenseCredentials);
            var results = new ConcurrentBag<TextAnalysisResponse>();
            var tasks = Enumerable.Range(0, 10)
                .Select(
                    id => new TextAnalysisRequest(
                        req.Text + $@" {id}",
                        req.Reports,
                        req.Style,
                        req.Language,
                        LicenseCredentials))
                .Select(async r => results.Add(await Api.TextPostAsync(r)))
                .ToArray();
            Task.WaitAll(tasks);
            Assert.That(results, Is.Not.Empty);
            Assert.That(results.Count, Is.EqualTo(10));
        }
    }
}