/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AnalysisSummaryGraph
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalysisSummaryGraphTests
    {
        // TODO uncomment below to declare an instance variable for AnalysisSummaryGraph
        //private AnalysisSummaryGraph instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnalysisSummaryGraph
            //instance = new AnalysisSummaryGraph();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalysisSummaryGraph
        /// </summary>
        [Test]
        public void AnalysisSummaryGraphInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnalysisSummaryGraph
            //Assert.IsInstanceOfType<AnalysisSummaryGraph> (instance, "variable 'instance' is a AnalysisSummaryGraph");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
