/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AnalysisSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalysisSettingsTests
    {
        // TODO uncomment below to declare an instance variable for AnalysisSettings
        //private AnalysisSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnalysisSettings
            //instance = new AnalysisSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalysisSettings
        /// </summary>
        [Test]
        public void AnalysisSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnalysisSettings
            //Assert.IsInstanceOfType<AnalysisSettings> (instance, "variable 'instance' is a AnalysisSettings");
        }

        /// <summary>
        /// Test the property 'ShortestAverageSentenceLength'
        /// </summary>
        [Test]
        public void ShortestAverageSentenceLengthTest()
        {
            // TODO unit test for the property 'ShortestAverageSentenceLength'
        }
        /// <summary>
        /// Test the property 'LongestAverageSentenceLength'
        /// </summary>
        [Test]
        public void LongestAverageSentenceLengthTest()
        {
            // TODO unit test for the property 'LongestAverageSentenceLength'
        }
        /// <summary>
        /// Test the property 'LongestIndividualSentence'
        /// </summary>
        [Test]
        public void LongestIndividualSentenceTest()
        {
            // TODO unit test for the property 'LongestIndividualSentence'
        }
        /// <summary>
        /// Test the property 'HighestPassiveIndex'
        /// </summary>
        [Test]
        public void HighestPassiveIndexTest()
        {
            // TODO unit test for the property 'HighestPassiveIndex'
        }
        /// <summary>
        /// Test the property 'MaxGlueIndex'
        /// </summary>
        [Test]
        public void MaxGlueIndexTest()
        {
            // TODO unit test for the property 'MaxGlueIndex'
        }
        /// <summary>
        /// Test the property 'MinSentenceVariety'
        /// </summary>
        [Test]
        public void MinSentenceVarietyTest()
        {
            // TODO unit test for the property 'MinSentenceVariety'
        }
        /// <summary>
        /// Test the property 'HighestPronounPercentage'
        /// </summary>
        [Test]
        public void HighestPronounPercentageTest()
        {
            // TODO unit test for the property 'HighestPronounPercentage'
        }
        /// <summary>
        /// Test the property 'LowestPronounPercentage'
        /// </summary>
        [Test]
        public void LowestPronounPercentageTest()
        {
            // TODO unit test for the property 'LowestPronounPercentage'
        }
        /// <summary>
        /// Test the property 'HighestAcademicPronounPercentage'
        /// </summary>
        [Test]
        public void HighestAcademicPronounPercentageTest()
        {
            // TODO unit test for the property 'HighestAcademicPronounPercentage'
        }
        /// <summary>
        /// Test the property 'HighestInitialPronounPercentage'
        /// </summary>
        [Test]
        public void HighestInitialPronounPercentageTest()
        {
            // TODO unit test for the property 'HighestInitialPronounPercentage'
        }
        /// <summary>
        /// Test the property 'LowestInitialPronounPercentage'
        /// </summary>
        [Test]
        public void LowestInitialPronounPercentageTest()
        {
            // TODO unit test for the property 'LowestInitialPronounPercentage'
        }
        /// <summary>
        /// Test the property 'LowestWeWeScore'
        /// </summary>
        [Test]
        public void LowestWeWeScoreTest()
        {
            // TODO unit test for the property 'LowestWeWeScore'
        }
        /// <summary>
        /// Test the property 'LongestAverageParagraphLength'
        /// </summary>
        [Test]
        public void LongestAverageParagraphLengthTest()
        {
            // TODO unit test for the property 'LongestAverageParagraphLength'
        }

    }

}
