/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AnalysisSummaryItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalysisSummaryItemTests
    {
        // TODO uncomment below to declare an instance variable for AnalysisSummaryItem
        //private AnalysisSummaryItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnalysisSummaryItem
            //instance = new AnalysisSummaryItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalysisSummaryItem
        /// </summary>
        [Test]
        public void AnalysisSummaryItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnalysisSummaryItem
            //Assert.IsInstanceOfType<AnalysisSummaryItem> (instance, "variable 'instance' is a AnalysisSummaryItem");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Graph'
        /// </summary>
        [Test]
        public void GraphTest()
        {
            // TODO unit test for the property 'Graph'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'UrlText'
        /// </summary>
        [Test]
        public void UrlTextTest()
        {
            // TODO unit test for the property 'UrlText'
        }
        /// <summary>
        /// Test the property 'SubItems'
        /// </summary>
        [Test]
        public void SubItemsTest()
        {
            // TODO unit test for the property 'SubItems'
        }
        /// <summary>
        /// Test the property 'IsPositive'
        /// </summary>
        [Test]
        public void IsPositiveTest()
        {
            // TODO unit test for the property 'IsPositive'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Test]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }
        /// <summary>
        /// Test the property 'NumIssues'
        /// </summary>
        [Test]
        public void NumIssuesTest()
        {
            // TODO unit test for the property 'NumIssues'
        }

    }

}
