/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AnalysisSummaryGraphItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalysisSummaryGraphItemTests
    {
        // TODO uncomment below to declare an instance variable for AnalysisSummaryGraphItem
        //private AnalysisSummaryGraphItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnalysisSummaryGraphItem
            //instance = new AnalysisSummaryGraphItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalysisSummaryGraphItem
        /// </summary>
        [Test]
        public void AnalysisSummaryGraphItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnalysisSummaryGraphItem
            //Assert.IsInstanceOfType<AnalysisSummaryGraphItem> (instance, "variable 'instance' is a AnalysisSummaryGraphItem");
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'SubCategory'
        /// </summary>
        [Test]
        public void SubCategoryTest()
        {
            // TODO unit test for the property 'SubCategory'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
