/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AsyncResponseSummaryAnalysisResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsyncResponseSummaryAnalysisResponseTests
    {
        // TODO uncomment below to declare an instance variable for AsyncResponseSummaryAnalysisResponse
        //private AsyncResponseSummaryAnalysisResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsyncResponseSummaryAnalysisResponse
            //instance = new AsyncResponseSummaryAnalysisResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsyncResponseSummaryAnalysisResponse
        /// </summary>
        [Test]
        public void AsyncResponseSummaryAnalysisResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsyncResponseSummaryAnalysisResponse
            //Assert.IsInstanceOfType<AsyncResponseSummaryAnalysisResponse> (instance, "variable 'instance' is a AsyncResponseSummaryAnalysisResponse");
        }


        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
