/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing AsyncResponseHtmlAnalysisResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsyncResponseHtmlAnalysisResponseTests
    {
        // TODO uncomment below to declare an instance variable for AsyncResponseHtmlAnalysisResponse
        //private AsyncResponseHtmlAnalysisResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsyncResponseHtmlAnalysisResponse
            //instance = new AsyncResponseHtmlAnalysisResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsyncResponseHtmlAnalysisResponse
        /// </summary>
        [Test]
        public void AsyncResponseHtmlAnalysisResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsyncResponseHtmlAnalysisResponse
            //Assert.IsInstanceOfType<AsyncResponseHtmlAnalysisResponse> (instance, "variable 'instance' is a AsyncResponseHtmlAnalysisResponse");
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
