/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing ContextualThesaurusRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContextualThesaurusRequestTests
    {
        // TODO uncomment below to declare an instance variable for ContextualThesaurusRequest
        //private ContextualThesaurusRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContextualThesaurusRequest
            //instance = new ContextualThesaurusRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContextualThesaurusRequest
        /// </summary>
        [Test]
        public void ContextualThesaurusRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContextualThesaurusRequest
            //Assert.IsInstanceOfType<ContextualThesaurusRequest> (instance, "variable 'instance' is a ContextualThesaurusRequest");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'ContextStart'
        /// </summary>
        [Test]
        public void ContextStartTest()
        {
            // TODO unit test for the property 'ContextStart'
        }
        /// <summary>
        /// Test the property 'ContextEnd'
        /// </summary>
        [Test]
        public void ContextEndTest()
        {
            // TODO unit test for the property 'ContextEnd'
        }

    }

}
