/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing DocTag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocTagTests
    {
        // TODO uncomment below to declare an instance variable for DocTag
        //private DocTag instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocTag
            //instance = new DocTag();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocTag
        /// </summary>
        [Test]
        public void DocTagInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocTag
            //Assert.IsInstanceOfType<DocTag> (instance, "variable 'instance' is a DocTag");
        }


        /// <summary>
        /// Test the property 'StartPos'
        /// </summary>
        [Test]
        public void StartPosTest()
        {
            // TODO unit test for the property 'StartPos'
        }
        /// <summary>
        /// Test the property 'EndPos'
        /// </summary>
        [Test]
        public void EndPosTest()
        {
            // TODO unit test for the property 'EndPos'
        }
        /// <summary>
        /// Test the property 'Report'
        /// </summary>
        [Test]
        public void ReportTest()
        {
            // TODO unit test for the property 'Report'
        }
        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Test]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CategoryDisplayName'
        /// </summary>
        [Test]
        public void CategoryDisplayNameTest()
        {
            // TODO unit test for the property 'CategoryDisplayName'
        }
        /// <summary>
        /// Test the property 'Subcategory'
        /// </summary>
        [Test]
        public void SubcategoryTest()
        {
            // TODO unit test for the property 'Subcategory'
        }
        /// <summary>
        /// Test the property 'Hint'
        /// </summary>
        [Test]
        public void HintTest()
        {
            // TODO unit test for the property 'Hint'
        }
        /// <summary>
        /// Test the property 'Suggestions'
        /// </summary>
        [Test]
        public void SuggestionsTest()
        {
            // TODO unit test for the property 'Suggestions'
        }
        /// <summary>
        /// Test the property 'IsSubTag'
        /// </summary>
        [Test]
        public void IsSubTagTest()
        {
            // TODO unit test for the property 'IsSubTag'
        }
        /// <summary>
        /// Test the property 'HelpId'
        /// </summary>
        [Test]
        public void HelpIdTest()
        {
            // TODO unit test for the property 'HelpId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
