/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing HtmlAnalysisRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlAnalysisRequestTests
    {
        // TODO uncomment below to declare an instance variable for HtmlAnalysisRequest
        //private HtmlAnalysisRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlAnalysisRequest
            //instance = new HtmlAnalysisRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlAnalysisRequest
        /// </summary>
        [Test]
        public void HtmlAnalysisRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlAnalysisRequest
            //Assert.IsInstanceOfType<HtmlAnalysisRequest> (instance, "variable 'instance' is a HtmlAnalysisRequest");
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Reports'
        /// </summary>
        [Test]
        public void ReportsTest()
        {
            // TODO unit test for the property 'Reports'
        }
        /// <summary>
        /// Test the property 'Style'
        /// </summary>
        [Test]
        public void StyleTest()
        {
            // TODO unit test for the property 'Style'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

    }

}
