/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing HtmlAnalysisResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlAnalysisResponseTests
    {
        // TODO uncomment below to declare an instance variable for HtmlAnalysisResponse
        //private HtmlAnalysisResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlAnalysisResponse
            //instance = new HtmlAnalysisResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlAnalysisResponse
        /// </summary>
        [Test]
        public void HtmlAnalysisResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlAnalysisResponse
            //Assert.IsInstanceOfType<HtmlAnalysisResponse> (instance, "variable 'instance' is a HtmlAnalysisResponse");
        }


        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'WordCount'
        /// </summary>
        [Test]
        public void WordCountTest()
        {
            // TODO unit test for the property 'WordCount'
        }
        /// <summary>
        /// Test the property 'Summaries'
        /// </summary>
        [Test]
        public void SummariesTest()
        {
            // TODO unit test for the property 'Summaries'
        }

    }

}
