/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing HttpStatusCodeResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HttpStatusCodeResultTests
    {
        // TODO uncomment below to declare an instance variable for HttpStatusCodeResult
        //private HttpStatusCodeResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HttpStatusCodeResult
            //instance = new HttpStatusCodeResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HttpStatusCodeResult
        /// </summary>
        [Test]
        public void HttpStatusCodeResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HttpStatusCodeResult
            //Assert.IsInstanceOfType<HttpStatusCodeResult> (instance, "variable 'instance' is a HttpStatusCodeResult");
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Test]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }

    }

}
