/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing Report
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportTests
    {
        // TODO uncomment below to declare an instance variable for Report
        //private Report instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Report
            //instance = new Report();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Report
        /// </summary>
        [Test]
        public void ReportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Report
            //Assert.IsInstanceOfType<Report> (instance, "variable 'instance' is a Report");
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Sample'
        /// </summary>
        [Test]
        public void SampleTest()
        {
            // TODO unit test for the property 'Sample'
        }
        /// <summary>
        /// Test the property 'Footer'
        /// </summary>
        [Test]
        public void FooterTest()
        {
            // TODO unit test for the property 'Footer'
        }
        /// <summary>
        /// Test the property 'Issues'
        /// </summary>
        [Test]
        public void IssuesTest()
        {
            // TODO unit test for the property 'Issues'
        }

    }

}
