/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing SummaryAnalysisResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummaryAnalysisResponseTests
    {
        // TODO uncomment below to declare an instance variable for SummaryAnalysisResponse
        //private SummaryAnalysisResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummaryAnalysisResponse
            //instance = new SummaryAnalysisResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummaryAnalysisResponse
        /// </summary>
        [Test]
        public void SummaryAnalysisResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummaryAnalysisResponse
            //Assert.IsInstanceOfType<SummaryAnalysisResponse> (instance, "variable 'instance' is a SummaryAnalysisResponse");
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

    }

}
