/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing TextAnalysisResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TextAnalysisResponseTests
    {
        // TODO uncomment below to declare an instance variable for TextAnalysisResponse
        //private TextAnalysisResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TextAnalysisResponse
            //instance = new TextAnalysisResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TextAnalysisResponse
        /// </summary>
        [Test]
        public void TextAnalysisResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TextAnalysisResponse
            //Assert.IsInstanceOfType<TextAnalysisResponse> (instance, "variable 'instance' is a TextAnalysisResponse");
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'WordCount'
        /// </summary>
        [Test]
        public void WordCountTest()
        {
            // TODO unit test for the property 'WordCount'
        }
        /// <summary>
        /// Test the property 'Summaries'
        /// </summary>
        [Test]
        public void SummariesTest()
        {
            // TODO unit test for the property 'Summaries'
        }

    }

}
