/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing TupleInt32String
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TupleInt32StringTests
    {
        // TODO uncomment below to declare an instance variable for TupleInt32String
        //private TupleInt32String instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TupleInt32String
            //instance = new TupleInt32String();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TupleInt32String
        /// </summary>
        [Test]
        public void TupleInt32StringInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TupleInt32String
            //Assert.IsInstanceOfType<TupleInt32String> (instance, "variable 'instance' is a TupleInt32String");
        }

        /// <summary>
        /// Test the property 'Item1'
        /// </summary>
        [Test]
        public void Item1Test()
        {
            // TODO unit test for the property 'Item1'
        }
        /// <summary>
        /// Test the property 'Item2'
        /// </summary>
        [Test]
        public void Item2Test()
        {
            // TODO unit test for the property 'Item2'
        }

    }

}
