/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing UserDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserDocumentTests
    {
        // TODO uncomment below to declare an instance variable for UserDocument
        //private UserDocument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserDocument
            //instance = new UserDocument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserDocument
        /// </summary>
        [Test]
        public void UserDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserDocument
            //Assert.IsInstanceOfType<UserDocument> (instance, "variable 'instance' is a UserDocument");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Preview'
        /// </summary>
        [Test]
        public void PreviewTest()
        {
            // TODO unit test for the property 'Preview'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Test]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'AutoSaveLastModified'
        /// </summary>
        [Test]
        public void AutoSaveLastModifiedTest()
        {
            // TODO unit test for the property 'AutoSaveLastModified'
        }
        /// <summary>
        /// Test the property 'GrammarScore'
        /// </summary>
        [Test]
        public void GrammarScoreTest()
        {
            // TODO unit test for the property 'GrammarScore'
        }
        /// <summary>
        /// Test the property 'StyleScore'
        /// </summary>
        [Test]
        public void StyleScoreTest()
        {
            // TODO unit test for the property 'StyleScore'
        }
        /// <summary>
        /// Test the property 'SpellingScore'
        /// </summary>
        [Test]
        public void SpellingScoreTest()
        {
            // TODO unit test for the property 'SpellingScore'
        }
        /// <summary>
        /// Test the property 'TermScore'
        /// </summary>
        [Test]
        public void TermScoreTest()
        {
            // TODO unit test for the property 'TermScore'
        }
        /// <summary>
        /// Test the property 'OverallScore'
        /// </summary>
        [Test]
        public void OverallScoreTest()
        {
            // TODO unit test for the property 'OverallScore'
        }

    }

}
