/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProWritingAid.SDK.Api;
using ProWritingAid.SDK.Model;
using ProWritingAid.SDK.Client;
using System.Reflection;

namespace ProWritingAid.SDK.Test
{
    /// <summary>
    ///  Class for testing WordCloudRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WordCloudRequestTests
    {
        // TODO uncomment below to declare an instance variable for WordCloudRequest
        //private WordCloudRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WordCloudRequest
            //instance = new WordCloudRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WordCloudRequest
        /// </summary>
        [Test]
        public void WordCloudRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WordCloudRequest
            //Assert.IsInstanceOfType<WordCloudRequest> (instance, "variable 'instance' is a WordCloudRequest");
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Orientation'
        /// </summary>
        [Test]
        public void OrientationTest()
        {
            // TODO unit test for the property 'Orientation'
        }
        /// <summary>
        /// Test the property 'CaseMethod'
        /// </summary>
        [Test]
        public void CaseMethodTest()
        {
            // TODO unit test for the property 'CaseMethod'
        }
        /// <summary>
        /// Test the property 'PaletteName'
        /// </summary>
        [Test]
        public void PaletteNameTest()
        {
            // TODO unit test for the property 'PaletteName'
        }
        /// <summary>
        /// Test the property 'MaximumWordCount'
        /// </summary>
        [Test]
        public void MaximumWordCountTest()
        {
            // TODO unit test for the property 'MaximumWordCount'
        }
        /// <summary>
        /// Test the property 'RemoveCommonWords'
        /// </summary>
        [Test]
        public void RemoveCommonWordsTest()
        {
            // TODO unit test for the property 'RemoveCommonWords'
        }
        /// <summary>
        /// Test the property 'FontName'
        /// </summary>
        [Test]
        public void FontNameTest()
        {
            // TODO unit test for the property 'FontName'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'OnlySentimentWords'
        /// </summary>
        [Test]
        public void OnlySentimentWordsTest()
        {
            // TODO unit test for the property 'OnlySentimentWords'
        }
        /// <summary>
        /// Test the property 'Style'
        /// </summary>
        [Test]
        public void StyleTest()
        {
            // TODO unit test for the property 'Style'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

    }

}
