/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ProWritingAid.SDK.Client.SwaggerDateConverter;

namespace ProWritingAid.SDK.Model
{
    /** 
    * <summary>Thesaurus meaning in one context</summary> 
    */
    [DataContract]
    public partial class EntryMeaning :  IEquatable<EntryMeaning>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntryMeaning" /> class.
        /// </summary>
        /// <param name="Meaning">Meaning.</param>
        /// <param name="PartOfSpeech">PartOfSpeech.</param>
        /// <param name="Synonyms">Synonyms.</param>
        public EntryMeaning(string Meaning = default(string), string PartOfSpeech = default(string), List<string> Synonyms = default(List<string>))
        {
            this.Meaning = Meaning;
            this.PartOfSpeech = PartOfSpeech;
            this.Synonyms = Synonyms;
        }
        
        /// <summary>
        /// Gets or Sets Meaning
        /// </summary>
        [DataMember(Name="Meaning", EmitDefaultValue=false)]
        public string Meaning { get; set; }

        /// <summary>
        /// Gets or Sets PartOfSpeech
        /// </summary>
        [DataMember(Name="PartOfSpeech", EmitDefaultValue=false)]
        public string PartOfSpeech { get; set; }

        /// <summary>
        /// Gets or Sets Synonyms
        /// </summary>
        [DataMember(Name="Synonyms", EmitDefaultValue=false)]
        public List<string> Synonyms { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EntryMeaning {\n");
            sb.Append("  Meaning: ").Append(Meaning).Append("\n");
            sb.Append("  PartOfSpeech: ").Append(PartOfSpeech).Append("\n");
            sb.Append("  Synonyms: ").Append(Synonyms).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as EntryMeaning);
        }

        /// <summary>
        /// Returns true if EntryMeaning instances are equal
        /// </summary>
        /// <param name="other">Instance of EntryMeaning to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntryMeaning other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Meaning == other.Meaning ||
                    this.Meaning != null &&
                    this.Meaning.Equals(other.Meaning)
                ) && 
                (
                    this.PartOfSpeech == other.PartOfSpeech ||
                    this.PartOfSpeech != null &&
                    this.PartOfSpeech.Equals(other.PartOfSpeech)
                ) && 
                (
                    this.Synonyms == other.Synonyms ||
                    this.Synonyms != null &&
                    this.Synonyms.SequenceEqual(other.Synonyms)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Meaning != null)
                    hash = hash * 59 + this.Meaning.GetHashCode();
                if (this.PartOfSpeech != null)
                    hash = hash * 59 + this.PartOfSpeech.GetHashCode();
                if (this.Synonyms != null)
                    hash = hash * 59 + this.Synonyms.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
