/* 
 * ProWritingAid.API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ProWritingAid.SDK.Model
{
    /// <summary>
    /// HtmlAnalysisRequest
    /// </summary>
    [DataContract]
    public class HtmlAnalysisRequest : AnalysisRequestBase, IEquatable<HtmlAnalysisRequest>
    {
        /// <summary>
        /// Document's writing style
        /// </summary>
        /// <value>Document's writing style</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StyleEnum
        {
            
            /// <summary>
            /// Enum NotSet for "NotSet"
            /// </summary>
            [EnumMember(Value = "NotSet")]
            NotSet,
            
            /// <summary>
            /// Enum General for "General"
            /// </summary>
            [EnumMember(Value = "General")]
            General,
            
            /// <summary>
            /// Enum Academic for "Academic"
            /// </summary>
            [EnumMember(Value = "Academic")]
            Academic,
            
            /// <summary>
            /// Enum Business for "Business"
            /// </summary>
            [EnumMember(Value = "Business")]
            Business,
            
            /// <summary>
            /// Enum Technical for "Technical"
            /// </summary>
            [EnumMember(Value = "Technical")]
            Technical,
            
            /// <summary>
            /// Enum Creative for "Creative"
            /// </summary>
            [EnumMember(Value = "Creative")]
            Creative,
            
            /// <summary>
            /// Enum Casual for "Casual"
            /// </summary>
            [EnumMember(Value = "Casual")]
            Casual,
            
            /// <summary>
            /// Enum Web for "Web"
            /// </summary>
            [EnumMember(Value = "Web")]
            Web
        }

        /// <summary>
        /// Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks>
        /// </summary>
        /// <value>Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks></value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LanguageEnum
        {
            
            /// <summary>
            /// Enum EnUS for "en_US"
            /// </summary>
            [EnumMember(Value = "en_US")]
            EnUS,
            
            /// <summary>
            /// Enum EnUK for "en_UK"
            /// </summary>
            [EnumMember(Value = "en_UK")]
            EnUK,
            
            /// <summary>
            /// Enum En for "en"
            /// </summary>
            [EnumMember(Value = "en")]
            En,
            
            /// <summary>
            /// Enum Es for "es"
            /// </summary>
            [EnumMember(Value = "es")]
            Es
        }

        /// <summary>
        /// Document's writing style
        /// </summary>
        /// <value>Document's writing style</value>
        [DataMember(Name="Style", EmitDefaultValue=false)]
        public StyleEnum? Style { get; set; }
        /// <summary>
        /// Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks>
        /// </summary>
        /// <value>Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks></value>
        [DataMember(Name="Language", EmitDefaultValue=false)]
        public LanguageEnum? Language { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HtmlAnalysisRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HtmlAnalysisRequest() : base(null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HtmlAnalysisRequest" /> class.
        /// </summary>
        /// <param name="Html">Html to be processed (required).</param>
        /// <param name="Reports">List of reports   &lt;example&gt;  [\&quot;grammar\&quot;,\&quot;overused\&quot;]  &lt;/example&gt;&lt;remarks&gt;  List of currently supported reports:  acronym,alliteration,allrepeats,allsentences,  cliche,closerepeat,combo,complex,consistency,  core,corporate,dialog,diction,dva,eloquence,  grammar,grammarplus,homonym,house,initial,nlp,  overused,overusedonly,overview,pacing,passive,  phrases,plagiarism,plength,preadability,slength,  ssentences,ssentences_noglue,structure,thesaurus,  transition,vague,wordcloud,wordsandphrases,wordsphrases  &lt;/remarks&gt; (required).</param>
        /// <param name="Style">Document&#39;s writing style (required).</param>
        /// <param name="Language">Document&#39;s language  &lt;remarks&gt;  Set correct UK/US language to get region-specific suggestions  &lt;/remarks&gt; (required).</param>
        /// <param name="credentials"></param>
        public HtmlAnalysisRequest(
            string Html,
            List<string> Reports,
            StyleEnum? Style,
            LanguageEnum? Language,
            RequestCredentials credentials) : base(credentials)
        {
            // to ensure "Html" is required (not null)
            if (Html == null)
            {
                throw new InvalidDataException("Html is a required property for HtmlAnalysisRequest and cannot be null");
            }
            else
            {
                this.Html = Html;
            }
            // to ensure "Reports" is required (not null)
            if (Reports == null)
            {
                throw new InvalidDataException("Reports is a required property for HtmlAnalysisRequest and cannot be null");
            }
            else
            {
                this.Reports = Reports;
            }
            // to ensure "Style" is required (not null)
            if (Style == null)
            {
                throw new InvalidDataException("Style is a required property for HtmlAnalysisRequest and cannot be null");
            }
            else
            {
                this.Style = Style;
            }
            // to ensure "Language" is required (not null)
            if (Language == null)
            {
                throw new InvalidDataException("Language is a required property for HtmlAnalysisRequest and cannot be null");
            }
            else
            {
                this.Language = Language;
            }
			if (credentials == null)
            {
                throw new ArgumentNullException(nameof(credentials));
            }
        }
        
        /// <summary>
        /// Html to be processed
        /// </summary>
        /// <value>Html to be processed</value>
        [DataMember(Name="Html", EmitDefaultValue=false)]
        public string Html { get; set; }
        /// <summary>
        /// List of reports   &lt;example&gt;  [\&quot;grammar\&quot;,\&quot;overused\&quot;]  &lt;/example&gt;&lt;remarks&gt;  List of currently supported reports:  acronym,alliteration,allrepeats,allsentences,  cliche,closerepeat,combo,complex,consistency,  core,corporate,dialog,diction,dva,eloquence,  grammar,grammarplus,homonym,house,initial,nlp,  overused,overusedonly,overview,pacing,passive,  phrases,plagiarism,plength,preadability,slength,  ssentences,ssentences_noglue,structure,thesaurus,  transition,vague,wordcloud,wordsandphrases,wordsphrases  &lt;/remarks&gt;
        /// </summary>
        /// <value>List of reports   &lt;example&gt;  [\&quot;grammar\&quot;,\&quot;overused\&quot;]  &lt;/example&gt;&lt;remarks&gt;  List of currently supported reports:  acronym,alliteration,allrepeats,allsentences,  cliche,closerepeat,combo,complex,consistency,  core,corporate,dialog,diction,dva,eloquence,  grammar,grammarplus,homonym,house,initial,nlp,  overused,overusedonly,overview,pacing,passive,  phrases,plagiarism,plength,preadability,slength,  ssentences,ssentences_noglue,structure,thesaurus,  transition,vague,wordcloud,wordsandphrases,wordsphrases  &lt;/remarks&gt;</value>
        [DataMember(Name="Reports", EmitDefaultValue=false)]
        public List<string> Reports { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HtmlAnalysisRequest {\n");
            sb.Append("  Html: ").Append(Html).Append("\n");
            sb.Append("  Reports: ").Append(Reports).Append("\n");
            sb.Append("  Style: ").Append(Style).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as HtmlAnalysisRequest);
        }

        /// <summary>
        /// Returns true if HtmlAnalysisRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of HtmlAnalysisRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HtmlAnalysisRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Html == other.Html ||
                    this.Html != null &&
                    this.Html.Equals(other.Html)
                ) && 
                (
                    this.Reports == other.Reports ||
                    this.Reports != null &&
                    this.Reports.SequenceEqual(other.Reports)
                ) && 
                (
                    this.Style == other.Style ||
                    this.Style != null &&
                    this.Style.Equals(other.Style)
                ) && 
                (
                    this.Language == other.Language ||
                    this.Language != null &&
                    this.Language.Equals(other.Language)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Html != null)
                    hash = hash * 59 + this.Html.GetHashCode();
                if (this.Reports != null)
                    hash = hash * 59 + this.Reports.GetHashCode();
                if (this.Style != null)
                    hash = hash * 59 + this.Style.GetHashCode();
                if (this.Language != null)
                    hash = hash * 59 + this.Language.GetHashCode();
                return hash;
            }
        }
    }

}
