/* 
 * ProWritingAid.API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ProWritingAid.SDK.Model
{
    /// <summary>
    /// SummaryAnalysisRequest
    /// </summary>
    [DataContract]
    public partial class SummaryAnalysisRequest : AnalysisRequestBase, IEquatable<SummaryAnalysisRequest>
    {
        /// <summary>
        /// Document's writing style
        /// </summary>
        /// <value>Document's writing style</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StyleEnum
        {
            
            /// <summary>
            /// Enum NotSet for "NotSet"
            /// </summary>
            [EnumMember(Value = "NotSet")]
            NotSet,
            
            /// <summary>
            /// Enum General for "General"
            /// </summary>
            [EnumMember(Value = "General")]
            General,
            
            /// <summary>
            /// Enum Academic for "Academic"
            /// </summary>
            [EnumMember(Value = "Academic")]
            Academic,
            
            /// <summary>
            /// Enum Business for "Business"
            /// </summary>
            [EnumMember(Value = "Business")]
            Business,
            
            /// <summary>
            /// Enum Technical for "Technical"
            /// </summary>
            [EnumMember(Value = "Technical")]
            Technical,
            
            /// <summary>
            /// Enum Creative for "Creative"
            /// </summary>
            [EnumMember(Value = "Creative")]
            Creative,
            
            /// <summary>
            /// Enum Casual for "Casual"
            /// </summary>
            [EnumMember(Value = "Casual")]
            Casual,
            
            /// <summary>
            /// Enum Web for "Web"
            /// </summary>
            [EnumMember(Value = "Web")]
            Web
        }

        /// <summary>
        /// Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks>
        /// </summary>
        /// <value>Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks></value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LanguageEnum
        {
            
            /// <summary>
            /// Enum EnUS for "en_US"
            /// </summary>
            [EnumMember(Value = "en_US")]
            EnUS,
            
            /// <summary>
            /// Enum EnUK for "en_UK"
            /// </summary>
            [EnumMember(Value = "en_UK")]
            EnUK,
            
            /// <summary>
            /// Enum En for "en"
            /// </summary>
            [EnumMember(Value = "en")]
            En,
            
            /// <summary>
            /// Enum Es for "es"
            /// </summary>
            [EnumMember(Value = "es")]
            Es
        }

        /// <summary>
        /// Document's writing style
        /// </summary>
        /// <value>Document's writing style</value>
        [DataMember(Name="Style", EmitDefaultValue=false)]
        public StyleEnum? Style { get; set; }
        /// <summary>
        /// Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks>
        /// </summary>
        /// <value>Document's language  <remarks>  Set correct UK/US language to get region-specific suggestions  </remarks></value>
        [DataMember(Name="Language", EmitDefaultValue=false)]
        public LanguageEnum? Language { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SummaryAnalysisRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SummaryAnalysisRequest():base(null) { }

        /// <summary>
        /// Initializes a new instance of the <see cref="SummaryAnalysisRequest" /> class.
        /// </summary>
        /// <param name="Text">Text to be analyzed (required).</param>
        /// <param name="Settings">Analysis settings (required).</param>
        /// <param name="Style">Document&#39;s writing style (required).</param>
        /// <param name="Language">Document&#39;s language  &lt;remarks&gt;  Set correct UK/US language to get region-specific suggestions  &lt;/remarks&gt; (required).</param>
        /// <param name="credentials">auth credentials</param>
        public SummaryAnalysisRequest(
            string Text,
            AnalysisSettings Settings,
            StyleEnum? Style,
            LanguageEnum? Language,
            RequestCredentials credentials): base(credentials)
        {
            // to ensure "Text" is required (not null)
            if (Text == null)
            {
                throw new InvalidDataException("Text is a required property for SummaryAnalysisRequest and cannot be null");
            }
            else
            {
                this.Text = Text;
            }
            // to ensure "Settings" is required (not null)
            if (Settings == null)
            {
                throw new InvalidDataException("Settings is a required property for SummaryAnalysisRequest and cannot be null");
            }
            else
            {
                this.Settings = Settings;
            }
            // to ensure "Style" is required (not null)
            if (Style == null)
            {
                throw new InvalidDataException("Style is a required property for SummaryAnalysisRequest and cannot be null");
            }
            else
            {
                this.Style = Style;
            }
            // to ensure "Language" is required (not null)
            if (Language == null)
            {
                throw new InvalidDataException("Language is a required property for SummaryAnalysisRequest and cannot be null");
            }
            else
            {
                this.Language = Language;
            }
            if (credentials == null)
            {
                throw new ArgumentNullException(nameof(credentials));
            }
        }
        
        /// <summary>
        /// Text to be analyzed
        /// </summary>
        /// <value>Text to be analyzed</value>
        [DataMember(Name="Text", EmitDefaultValue=false)]
        public string Text { get; set; }
        /// <summary>
        /// Analysis settings
        /// </summary>
        /// <value>Analysis settings</value>
        [DataMember(Name="Settings", EmitDefaultValue=false)]
        public AnalysisSettings Settings { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SummaryAnalysisRequest {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("  Style: ").Append(Style).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SummaryAnalysisRequest);
        }

        /// <summary>
        /// Returns true if SummaryAnalysisRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of SummaryAnalysisRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SummaryAnalysisRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Text == other.Text ||
                    this.Text != null &&
                    this.Text.Equals(other.Text)
                ) && 
                (
                    this.Settings == other.Settings ||
                    this.Settings != null &&
                    this.Settings.Equals(other.Settings)
                ) && 
                (
                    this.Style == other.Style ||
                    this.Style != null &&
                    this.Style.Equals(other.Style)
                ) && 
                (
                    this.Language == other.Language ||
                    this.Language != null &&
                    this.Language.Equals(other.Language)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Text != null)
                    hash = hash * 59 + this.Text.GetHashCode();
                if (this.Settings != null)
                    hash = hash * 59 + this.Settings.GetHashCode();
                if (this.Style != null)
                    hash = hash * 59 + this.Style.GetHashCode();
                if (this.Language != null)
                    hash = hash * 59 + this.Language.GetHashCode();
                return hash;
            }
        }
    }

}
