/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ProWritingAid.SDK.Client.SwaggerDateConverter;

namespace ProWritingAid.SDK.Model
{
    /** 
    * <summary>ThesaurusResponse</summary> 
    */
    [DataContract]
    public partial class ThesaurusResponse :  IEquatable<ThesaurusResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThesaurusResponse" /> class.
        /// </summary>
        /// <param name="Word">The word that was searched.</param>
        /// <param name="Meanings">List of context-specific meanings.</param>
        public ThesaurusResponse(string Word = default(string), List<EntryMeaning> Meanings = default(List<EntryMeaning>))
        {
            this.Word = Word;
            this.Meanings = Meanings;
        }
        
        /// <summary>
        /// The word that was searched
        /// </summary>
        /// <value>The word that was searched</value>
        [DataMember(Name="Word", EmitDefaultValue=false)]
        public string Word { get; set; }

        /// <summary>
        /// List of context-specific meanings
        /// </summary>
        /// <value>List of context-specific meanings</value>
        [DataMember(Name="Meanings", EmitDefaultValue=false)]
        public List<EntryMeaning> Meanings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ThesaurusResponse {\n");
            sb.Append("  Word: ").Append(Word).Append("\n");
            sb.Append("  Meanings: ").Append(Meanings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ThesaurusResponse);
        }

        /// <summary>
        /// Returns true if ThesaurusResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ThesaurusResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ThesaurusResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Word == other.Word ||
                    this.Word != null &&
                    this.Word.Equals(other.Word)
                ) && 
                (
                    this.Meanings == other.Meanings ||
                    this.Meanings != null &&
                    this.Meanings.SequenceEqual(other.Meanings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Word != null)
                    hash = hash * 59 + this.Word.GetHashCode();
                if (this.Meanings != null)
                    hash = hash * 59 + this.Meanings.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
