/* 
 * ProWritingAid API V2
 *
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ProWritingAid.SDK.Client;
using ProWritingAid.SDK.Model;

namespace ProWritingAid.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITextApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>AsyncResponseTextAnalysisResponse</returns>
        AsyncResponseTextAnalysisResponse Get (string taskId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>ApiResponse of AsyncResponseTextAnalysisResponse</returns>
        ApiResponse<AsyncResponseTextAnalysisResponse> GetWithHttpInfo (string taskId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>AsyncResponseTextAnalysisResponse</returns>
        AsyncResponseTextAnalysisResponse Post (TextAnalysisRequest requestp);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>ApiResponse of AsyncResponseTextAnalysisResponse</returns>
        ApiResponse<AsyncResponseTextAnalysisResponse> PostWithHttpInfo (TextAnalysisRequest requestp);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>Task of AsyncResponseTextAnalysisResponse</returns>
        System.Threading.Tasks.Task<AsyncResponseTextAnalysisResponse> GetAsync (string taskId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>Task of ApiResponse (AsyncResponseTextAnalysisResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AsyncResponseTextAnalysisResponse>> GetAsyncWithHttpInfo (string taskId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>Task of AsyncResponseTextAnalysisResponse</returns>
        System.Threading.Tasks.Task<AsyncResponseTextAnalysisResponse> PostAsync (TextAnalysisRequest requestp);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>Task of ApiResponse (AsyncResponseTextAnalysisResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AsyncResponseTextAnalysisResponse>> PostAsyncWithHttpInfo (TextAnalysisRequest requestp);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TextApi : ITextApi
    {
        private ProWritingAid.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TextApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TextApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = ProWritingAid.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TextApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TextApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ProWritingAid.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ProWritingAid.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>AsyncResponseTextAnalysisResponse</returns>
        public AsyncResponseTextAnalysisResponse Get (string taskId)
        {
             ApiResponse<AsyncResponseTextAnalysisResponse> localVarResponse = GetWithHttpInfo(taskId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>ApiResponse of AsyncResponseTextAnalysisResponse</returns>
        public ApiResponse< AsyncResponseTextAnalysisResponse > GetWithHttpInfo (string taskId)
        {
            // verify the required parameter 'taskId' is set
            if (taskId == null)
                throw new ApiException(400, "Missing required parameter 'taskId' when calling TextApi->Get");

            var localVarPath = "/api/async/text/result/{taskId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (taskId != null) localVarPathParams.Add("taskId", Configuration.ApiClient.ParameterToString(taskId)); // path parameter

            // authentication (licenseCode) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("licenseCode")))
            {
                localVarHeaderParams["licenseCode"] = Configuration.GetApiKeyWithPrefix("licenseCode");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AsyncResponseTextAnalysisResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AsyncResponseTextAnalysisResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AsyncResponseTextAnalysisResponse)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>Task of AsyncResponseTextAnalysisResponse</returns>
        public async System.Threading.Tasks.Task<AsyncResponseTextAnalysisResponse> GetAsync (string taskId)
        {
             ApiResponse<AsyncResponseTextAnalysisResponse> localVarResponse = await GetAsyncWithHttpInfo(taskId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taskId"></param>
        /// <returns>Task of ApiResponse (AsyncResponseTextAnalysisResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AsyncResponseTextAnalysisResponse>> GetAsyncWithHttpInfo (string taskId)
        {
            // verify the required parameter 'taskId' is set
            if (taskId == null)
                throw new ApiException(400, "Missing required parameter 'taskId' when calling TextApi->Get");

            var localVarPath = "/api/async/text/result/{taskId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (taskId != null) localVarPathParams.Add("taskId", Configuration.ApiClient.ParameterToString(taskId)); // path parameter

            // authentication (licenseCode) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("licenseCode")))
            {
                localVarHeaderParams["licenseCode"] = Configuration.GetApiKeyWithPrefix("licenseCode");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AsyncResponseTextAnalysisResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AsyncResponseTextAnalysisResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AsyncResponseTextAnalysisResponse)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>AsyncResponseTextAnalysisResponse</returns>
        public AsyncResponseTextAnalysisResponse Post (TextAnalysisRequest requestp)
        {
             ApiResponse<AsyncResponseTextAnalysisResponse> localVarResponse = PostWithHttpInfo(requestp);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>ApiResponse of AsyncResponseTextAnalysisResponse</returns>
        public ApiResponse< AsyncResponseTextAnalysisResponse > PostWithHttpInfo (TextAnalysisRequest requestp)
        {
            // verify the required parameter 'requestp' is set
            if (requestp == null)
                throw new ApiException(400, "Missing required parameter 'requestp' when calling TextApi->Post");

            var localVarPath = "/api/async/text";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (requestp != null && requestp.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(requestp); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestp; // byte array
            }

            // authentication (licenseCode) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("licenseCode")))
            {
                localVarHeaderParams["licenseCode"] = Configuration.GetApiKeyWithPrefix("licenseCode");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Post", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AsyncResponseTextAnalysisResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AsyncResponseTextAnalysisResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AsyncResponseTextAnalysisResponse)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>Task of AsyncResponseTextAnalysisResponse</returns>
        public async System.Threading.Tasks.Task<AsyncResponseTextAnalysisResponse> PostAsync (TextAnalysisRequest requestp)
        {
             ApiResponse<AsyncResponseTextAnalysisResponse> localVarResponse = await PostAsyncWithHttpInfo(requestp);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ProWritingAid.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestp"></param>
        /// <returns>Task of ApiResponse (AsyncResponseTextAnalysisResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AsyncResponseTextAnalysisResponse>> PostAsyncWithHttpInfo (TextAnalysisRequest requestp)
        {
            // verify the required parameter 'requestp' is set
            if (requestp == null)
                throw new ApiException(400, "Missing required parameter 'requestp' when calling TextApi->Post");

            var localVarPath = "/api/async/text";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (requestp != null && requestp.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(requestp); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestp; // byte array
            }

            // authentication (licenseCode) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("licenseCode")))
            {
                localVarHeaderParams["licenseCode"] = Configuration.GetApiKeyWithPrefix("licenseCode");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Post", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AsyncResponseTextAnalysisResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AsyncResponseTextAnalysisResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AsyncResponseTextAnalysisResponse)));
        }

    }
}
